apiVersion: environment.cloudbees.com/v1alpha1
kind: GitRepository
metadata:
  name: ikurtz-declarative-pipelines-december-insurance-frontend                             
  namespace: previews
spec:
  url: https://github.com/ikurtz-declarative-pipelines-december/insurance-frontend.git
  apiTokenSecretRef:
    name: beedemo-dev-github-token
  autoUpdateContexts:                           
  - default
